name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          mkdir -p dist
          for GOOS in ${{ matrix.goos }}; do
            for GOARCH in ${{ matrix.goarch }}; do
              PACKAGE_NAME="fds-${GOOS}-${GOARCH}.tar.gz"
              env GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-w -s" -o dist/fds ./cmd
              tar czf dist/${PACKAGE_NAME} -C dist/ fds
              rm dist/fds
            done
          done

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
